### ISSUE TITLE
useQuery returns wrong data

### ISSUE THREAD

**Issue by bviebahn** [powersync-ja/powersync-js#517]
Hi,
I'm using the react-native SDK in my expo app, and I have this query:
```ts
const workItemsQuery = db
  .selectFrom("WorkItem")
  .select(["id", "assigneeId"])

export function useWorkItems(assigneeIds: string[] = []) {
  const query = useMemo(() => {
    let workItemsQueryModified = workItemsQuery

    if (assigneeIds.length > 0) {
      workItemsQueryModified = workItemsQueryModified.where(
        "WorkItem.assigneeId",
        "in",
        assigneeIds,
      )
    }

    return workItemsQueryModified
  }, [assigneeIds])

  const result = useQuery(query)

  return result
}
```

When I start the app we're fetching some user data, and then setting a default assignee, which gets passed to this query. I noticed that this filter doesn't always work, and the useQuery hook returns the unfiltered data even when the assignee filter is set. It seems that there is some kind of race condition, here are some things I noticed:
- If I add a limit to the query I don't have this issue anymore. There are a total of 3900 items in the database, if I limit the query to 500 I can't reproduce it anymore. I can still reproduce it with a limit of 1000. 
- Adding a timeout when setting this initial assignee filter also seems to "fix" it

I added some logs, and printed the sql query and the parameter, the length of the data, which should be 345 with the assignee filter applied, and 3900 without it, and also added this "didFilterWork" check:
```ts
  console.log("query", query.compile().sql, query.compile().parameters)
  console.log("result.data.lengh", result.data.length)
  console.log(
    "didFilterWork",
    result.data.every((workItem) => workItem.assigneeId === assigneeIds[0]),
  )
```

Here are the logs, I added some comments:
```
 // 1. There is no assignee filter and no data, query is still loading
 query select "id", "assigneeId" from "WorkItem" []
 result.data.lengh 0
 didFilterWork true

 // 2. assignee filter is set, still no data, query is still loading
 query select "id", "assigneeId" from "WorkItem" where "WorkItem"."assigneeId" in (?) ["6f470a95-6800-4c21-a677-64d09d25e76b"]
 result.data.lengh 0
 didFilterWork true

 // 3. correctly filtered data is returned
 query select "id", "assigneeId" from "WorkItem" where "WorkItem"."assigneeId" in (?) ["6f470a95-6800-4c21-a677-64d09d25e76b"]
 result.data.lengh 345
 didFilterWork true

 // 4. query is still the same, but the unfiltered data is returned
 query select "id", "assigneeId" from "WorkItem" where "WorkItem"."assigneeId" in (?) ["6f470a95-6800-4c21-a677-64d09d25e76b"]
 result.data.lengh 3900
 didFilterWork false
```

So I would guess that the initial query without the assignee filter is still running after the query with the assignee filter has returned, and then overrides the data.

I'm on the latest versions:
```
    "@journeyapps/react-native-quick-sqlite": "^2.4.0",
    "@powersync/kysely-driver": "^1.1.0",
    "@powersync/react-native": "^1.18.0",
```

Please let me know if you have any questions or need more info, thanks!

**Comment by HeinrichvonStein** [comment]
Hi @bviebahn. 

I'm busy trying to reproduce your issue. 
Could you provide your sync rules please?

Thanks
Hein

**Comment by bviebahn** [comment]
Hi @HeinrichvonStein 
We're still in early development and just sync everything at the moment:
```
bucket_definitions:
  global:
    data:
      - SELECT * FROM "User"
      - SELECT * FROM "WorkOrder"
      - SELECT * FROM "WorkItem"
      - SELECT * FROM "WorkInsight"
      - SELECT * FROM "WorkItemInsight"
      - SELECT * FROM "Event"
      - SELECT * FROM "Questionnaire"
      - SELECT * FROM "Organization"
      - SELECT * FROM "Membership"
      - SELECT * FROM "Project"
      - SELECT * FROM "Delivery"
      - SELECT * FROM "Role"
```
